server:
  port: ${APP_PORT:8761}
eureka:
  instance:
    hostname: localhost
  client:
#    是否把自己注册到eureka
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
spring:
  application:
    name: eureka-server
